version: v2.4
modules:
    - name: backbone
      services:
        - zookeeper
        - kafka
        - postgres
        - playground:mongo-v1
        - redis
        - nginx-ingress
        - kafka-connect
    - name: gatway
      services:
        - ifix-zuul:ifix-zuul-fef21ed-5      
    - name: core
      dependencies:
        - "backbone"
        - "gatway"    
      services:
        - keycloak:13.0.1
    - name: domain-services
      dependencies:
        - "core"
      services:
        - fiscal-event-post-processor:pk-department-entity-post-processor-1552df2-6
        - fiscal-event-service:develop-f6a32b0-4
        - ifix-department-entity-service:ifix-department-entity-service-3ba9c9f-3
        - ifix-master-data-service:rahu-310-47ceff2-7  
    - name: "frontend"             
      dependencies:
        - "domain-services"
      services:
        - citizen:citizen-v1.5.0-c1825dd69-291 
    - name: "olap"             
      services:
        - druid:0.21.1
        - metabase:v0.40.2      
    - name: m_iFix             #iFix
      dependencies:
        - "frontend"
        - "olap"
 