# Common Labels
labels:
  app: "frontend-mgramseva"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "mgramseva"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "frontend-mgramseva"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/mgramseva/"
  readinessProbePath: "/mgramseva/"
dashboard-url: ""


