{{- $serviceName := include "nginx-ingress.name" . -}}
{{- with index .Values "controller" "custom-headers" }}
{{- if index . }}
apiVersion: v1
data:
{{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
kind: ConfigMap
metadata:
  name: custom-headers
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }} 
{{- else }}   
  namespace: {{ .Values.namespace }}
{{- end }}  