apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.externalName }}
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: {{ .Values.name }} 
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }} 
{{- else }}   
  namespace: {{ .Values.namespace }}
{{- end }}  
spec:
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.name }}
          servicePort: {{ .Values.httpPort }}
        path: /{{ index $.Values "cluster-configs" "configmaps" "egov-config" "data" "s3-assets-bucket" }}/

