
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "name" . }}-pdb"
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }} 
{{- else }}   
  namespace: {{ .Values.namespace }}
{{- end }}  
  labels:
    app: {{ template "name" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
  maxUnavailable: 1