apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }} 
{{- else }}   
  namespace: {{ .Values.namespace }}
{{- end }}
  labels:
    app: {{ template "name" . }}
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: {{ template "name" . }}    