apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-headless
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }} 
{{- else }}   
  namespace: {{ .Values.namespace }}
{{- end }}
  labels:
    app: {{ template "name" . }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true" 
spec:
  ports:
    - port: 9092
      name: broker
  clusterIP: None  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  selector:
    app: {{ template "name" . }}
    